enable: "etcd"
etcd:
  rootDirectory: openim
  address: [ 43.163.80.39:12379 ]
  username: ""
  password: ""

kubernetes:
  namespace: default

rpcService:
  chat: chat-rpc-service
  admin: admin-rpc-service
