openIM:
  # OpenIM API address
  apiURL: http://127.0.0.1:10002
  # OpenIM secret key, must be consistent with OpenIM
  secret: owlIM123
  # OpenIM administrator userID, must be consistent with OpenIM
  adminUserID: imAdmin

chatAdmin:
   # Default username and password for the admin
  - "chatAdmin"

redPacket:
  apiURL: http://127.0.0.1:10086/v1
  timeout: 20


liveKit:
  url: "ws://127.0.0.1:7880" # LIVEKIT_URL, LiveKit server address and port
  key: "APIGPW3gnFTzqHH"
  secret: "23ztfSqsfQ8hKkHzHTl3Z4bvaxro0snjk5jwbp5p6Q3"
